name: terraform-todaoapp

on: 
  push:
    branches: 
    - main


jobs: 
  terraform-deploy:
    runs-on: ubuntu-latest
    # if: github.repository == terraform-todoapp-infra
    steps: 
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true

    

    
          

      
    
    
              
      
    
    
